services:
  postgres:
    image: postgres:16
    container_name: storeintel-db
    restart: always

    environment:
      POSTGRES_DB: storeintel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: storeintel-api
    restart: always

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/storeintel

    ports:
      - "8000:8000"

volumes:
  postgres_data: